### ISSUE TITLE
KeyError when running after installation

### ISSUE THREAD

**Issue by SamMatzko** [SamMatzko/Schach#2]
After downloading the `zip` file, and running `install.sh`, the app doesn't run when launched. When I run it in the terminal, it prints this error message:

```
Traceback (most recent call last):
  File "/home/user/.local/share/Schach-3.2.9/app.py", line 271, in do_activate
    self.create_actions()
  File "/home/user/.local/share/Schach-3.2.9/app.py", line 164, in create_actions
    self.set_action_accels()
  File "/home/user/.local/share/Schach-3.2.9/app.py", line 264, in set_action_accels
    self.set_accels_for_action("app.help-docs", self.actions["app.help-docs"])
KeyError: 'app.help-docs'
```

**Comment by SamMatzko** [comment]
This bug is fixed in the new Schach 3.2.10 release.
